-- MySQL Script generated by MySQL Workbench
-- Sat Apr 21 16:54:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema trainingpoint
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trainingpoint
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trainingpoint` DEFAULT CHARACTER SET utf8 ;
USE `trainingpoint` ;

-- -----------------------------------------------------
-- Table `trainingpoint`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trainingpoint`.`classes` (
  `classID` INT(11) NOT NULL,
  `className` VARCHAR(45) NOT NULL,
  `monitorName` VARCHAR(45) NOT NULL,
  `lecturerName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`classID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trainingpoint`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trainingpoint`.`users` (
  `userID` INT(11) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `isStudent` TINYINT(1) NOT NULL,
  `isMonitor` TINYINT(1) NOT NULL,
  `isLecturer` TINYINT(1) NOT NULL,
  `fullName` VARCHAR(45) NOT NULL,
  `classID` INT(11) NOT NULL,
  PRIMARY KEY (`userID`, `classID`),
  INDEX `classId_idx` (`classID` ASC),
  CONSTRAINT `classId`
    FOREIGN KEY (`classID`)
    REFERENCES `trainingpoint`.`classes` (`classID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trainingpoint`.`forms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trainingpoint`.`forms` (
  `formID` INT(11) NOT NULL,
  `userID` INT(11) NOT NULL,
  `formStatus` TINYINT(1) NOT NULL,
  `totalPoint` INT(11) NULL DEFAULT NULL,
  `studyingPoint` INT(11) NULL DEFAULT NULL,
  `regulationsPoint` INT(11) NULL DEFAULT NULL,
  `socialPoint` INT(11) NULL DEFAULT NULL,
  `otherPoint` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`formID`, `userID`),
  INDEX `studentID_idx` (`userID` ASC),
  CONSTRAINT `studentID`
    FOREIGN KEY (`userID`)
    REFERENCES `trainingpoint`.`users` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trainingpoint`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trainingpoint`.`notifications` (
  `notificationID` INT(11) NOT NULL,
  `message` MEDIUMTEXT NOT NULL,
  `senderID` INT(11) NOT NULL,
  `receiverID` INT(11) NOT NULL,
  `createdDate` DATETIME NOT NULL,
  PRIMARY KEY (`notificationID`, `senderID`),
  INDEX `senderID_idx` (`senderID` ASC),
  CONSTRAINT `senderID`
    FOREIGN KEY (`senderID`)
    REFERENCES `trainingpoint`.`users` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
